spring:
  profiles:
    active: db, core, os
  message:
    encoding: UTF-8

server:
  port: 8081

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.linlinjava.litemall.os:  DEBUG
    org.linlinjava.litemall:  ERROR