# 当前存储模式
# los，本地对象存储模式，上传图片保存在服务器中
# tos，腾讯对象存储模式，上传图片保存在腾讯云存储服务器中，请在tencent.properties配置相关信息
# tos，阿里云对象存储模式，上传图片保存在腾讯云存储服务器中，请在tencent.properties配置相关信息
activeStorage: los
#activeStorage: tos
#activeStorage: aos

# 开发者应该设置成自己的域名，必须附带http或者https
# 开发者可以查看OsStorageController.generateUrl
litemall.os.address: http://127.0.0.1
litemall.os.port: 8081